### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by InesArous** [FrederickXZhang/FgNLI#1]
Hello, thank you for the interesting work. The current repository is empty. I was wondering if your code and data are available elsewhere.

**Comment by FrederickXZhang** [comment]
Hi, Thanks for your interest in our work! Due to some technical reasons, I am not able to open-source the codebase for now. Yet, the codes will go public fairly soon! As for data, could you let me know your email address so that I can send a copy to you? You can reach out to me at xlfzhang@umich.edu, Thanks!
